### ISSUE TITLE
Script V5 does not find installation from VaultWarden

### ISSUE THREAD

**Issue by quorle** [tteck/Proxmox#904]
Tried the script V5 for the first time today, but the script does not find the installation of VaultWarden.

![Unbenannt](https://user-images.githubusercontent.com/38273154/210848558-197d8150-ab00-4d3c-8aad-453631727f0f.PNG)

**Comment by tteck** [comment]
You must have an older install. Hold on, I'll fix that...

**Comment by tteck** [comment]
Give it a try now

**Comment by quorle** [comment]
ok, now it works, but what do you have to select now? Or, what's the difference here?
![Unbenannt](https://user-images.githubusercontent.com/38273154/210849950-d867dab1-1c66-4e49-9017-bc9ee6cf2307.PNG)

**Comment by tteck** [comment]
- 1 updates VaultWarden 
- 2 updates Web-Vault
- 3 Shows Admin Token

I'd suggest selecting 3 and copy your token then go to IP:8000/admin, sign-in and go to the Diagnostics tab to see what needs updating

![Screenshot 2023-01-05 1 17 30 PM](https://user-images.githubusercontent.com/21342670/210852071-139afbc3-829b-4456-9165-1f77b5298b2d.png)

**Comment by quorle** [comment]
ok, when i select number 3, the following error comes up:

![Unbenannt](https://user-images.githubusercontent.com/38273154/210852790-292e378d-ad37-446b-97ca-98e8c65dd232.PNG)

**Comment by tteck** [comment]
try `cat /usr/bin/vaultwarden/.env`

**Comment by tteck** [comment]
Fixed
Had forgotten about older install path

**Comment by quorle** [comment]
the same problem

![Unbenannt](https://user-images.githubusercontent.com/38273154/210861200-b78a5280-6a00-41e6-8cbc-7f17a252ad7e.PNG)

**Comment by tteck** [comment]
It's been awhile, try this `cat /etc/vaultwarden.env `
We'll find the `.env` file eventually

**Comment by tteck** [comment]
I think it's fixed this time

**Comment by quorle** [comment]
I can find the vaultwarden.env and open it using your command. The token is also in this file. However, when I run the V5 script, the same error remains.
maybe the .env is here: /etc/vaultwarden.env

**Comment by tteck** [comment]
You may need to clear your browser cache

**Comment by tteck** [comment]
My fault, it will work this time. I typed `cat` twice

**Comment by quorle** [comment]
ok, i tried again. doesn't work yet. In addition, I tried position 1 of the script as an experiment, broke off and now Bad Gateway 502 comes up

**Comment by quorle** [comment]
OK, a reboot and i came on the Website

**Comment by tteck** [comment]
run `systemctl start vaultwarden.service`

**Comment by tteck** [comment]
Maybe create a new Container and move your data to the new one.
Support for the older install will end in upcoming scripts

**Comment by DirkTas67** [comment]
Hello,

I'm trying to find the vaultwarden.env file, I recently started with proxmox, have been running vaultwarden on Truenas for some time and it works great, but when I installed it on proxmox with the script it works localy fine but externaly I get an 503 service not available when I replace the ip and port in my pfSense haproxy setup. So I looked for some settings and maybe the ROCKET_ADDRESS in the env file will fix this. I just need to find it. 

I hope anybody can point me to where it is, a find . -print | grep -i vaultwarden.env didn't reveal anything.
